# -*- coding: utf-8 -*-
"""Apple logo animated using python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MI6jTuWOWJXdglf-W59YM2VDiqib4chg
"""

path=r"/content/sample_data/Apple body.xlsx"
path2=r"/content/sample_data/Apple leaf.xlsx"
import pandas as pd
from matplotlib import pyplot as plt

df=pd.read_excel(path)
df2=pd.read_excel(path2)

xcoord=list(df.Xcoord)
ycoord=list(df.Ycoord)
xleafcoord=list(df2.Xcoord)
yleafcoord=list(df2.Ycoord)
x=[]
y=[]

xl=[]
yl=[]

for i in range(len(ycoord)):
	x.append(xcoord[i])
	y.append(ycoord[i])
	if i<len(xleafcoord):
		xl.append(xleafcoord[i])
		yl.append(yleafcoord[i])

	plt.xlim(100, 500)
	plt.ylim(-60, 360)

	
	plt.plot(x, y,color='green')
	plt.plot(xl,yl, color = 'red')
	

	plt.pause(0.0001)

plt.show()